/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Alejandra G
 */
public class EspacioJF extends javax.swing.JFrame {
    public Cliente refCliente;
    public String name;
    /**
     * Creates new form EspacioJF
     */
    public EspacioJF() {
        initComponents();
        createMap(15,15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelEspacio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MI PLANETA");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 460, -1));

        panelEspacio.setLayout(new java.awt.GridLayout(1, 0));
        panelEspacio.setLayout(new java.awt.GridLayout(15,15));
        getContentPane().add(panelEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 460, 379));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 1230, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void ponerJF(JPanel otroJP){
        this.add(otroJP);
        otroJP.setLocation(526, 10);
    }
    public void addMensaje(String msj)
    {
        //txaMensajes.append(msj + "\n");
    } 
     public void createMap(int maxX,int maxY){
        //int maxX = 15;
        //int maxY = 15;
        panelEspacio.setOpaque(false);
        JPanel [ ][ ] map = new JPanel [maxX][maxY];

        for (int i = 0; i < maxX; i++) {

          for (int j = 0; j < maxY ; j++) {
            JPanel panel = new JPanel();
            map [i][j] = panel;
            JPanel panelci = new JPanel();
            panelci.setSize(5, 5);
            panelci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            //panelci.setBackground(Color.blue);
            panelci.setOpaque(false);
            panelEspacio.add(panelci);
              
          }
      }
        
     }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel panelEspacio;
    // End of variables declaration//GEN-END:variables
}
